# Generated by Django 3.2.12 on 2022-06-08 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=125)),
            ],
            options={
                'verbose_name_plural': 'Choix',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('G', 'Générale'), ('S', 'Software'), ('HW', 'Hardware'), ('HU', 'Human'), ('O', 'Organisationnel'), ('DM', 'Data Management')], default='G', max_length=65)),
                ('critere', models.CharField(default='', max_length=125)),
                ('choix', models.ManyToManyField(blank=True, related_name='questions_liees', to='maturite.Choix')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('choix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='maturite.choix')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='maturite.question')),
            ],
        ),
    ]
