# Generated by Django 3.2.12 on 2022-05-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('A faire', 'To Do'), ('En cours', 'In Progress'), ('Fait', 'Done')], default='A faire', max_length=25),
        ),
    ]
