# Generated by Django 3.2.12 on 2022-04-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publication immédiate ?'),
        ),
    ]
