# Generated by Django 3.2.12 on 2022-04-25 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilisateur', '0003_alter_kwgperson_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwgperson',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personne', to=settings.AUTH_USER_MODEL),
        ),
    ]
