# Generated by Django 3.2.12 on 2022-06-06 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rudi.models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('identification', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('fichier', models.FileField(max_length=255, upload_to=rudi.models.get_doc_filename, verbose_name='Document')),
                ('nom', models.CharField(blank=True, help_text='Un nom courant du fichier', max_length=125, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('etat', models.IntegerField(choices=[(0, 'Conception'), (1, 'Partage'), (2, 'Publication'), (3, 'Archivage')], default=0)),
                ('validation', models.CharField(choices=[('AA', 'A approuver'), ('A', 'Approuvé'), ('AC', 'Approuvé et Commenté'), ('NA', 'Non Approuvé')], default='AA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDocument',
            fields=[
                ('identification', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=36)),
                ('fichier', models.TextField(max_length=255, verbose_name='Document')),
                ('nom', models.CharField(blank=True, help_text='Un nom courant du fichier', max_length=125, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('etat', models.IntegerField(choices=[(0, 'Conception'), (1, 'Partage'), (2, 'Publication'), (3, 'Archivage')], default=0)),
                ('validation', models.CharField(choices=[('AA', 'A approuver'), ('A', 'Approuvé'), ('AC', 'Approuvé et Commenté'), ('NA', 'Non Approuvé')], default='AA', max_length=2)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical document',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
