# Generated by Django 3.2.12 on 2022-04-30 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_historicaldocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='document',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='modified_by',
        ),
    ]
