# Generated by Django 3.2.12 on 2022-05-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplantationScolaire',
            fields=[
                ('georefpostaladdress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.georefpostaladdress')),
                ('fase_imp', models.CharField(blank=True, max_length=6, null=True)),
                ('niveau', models.IntegerField(choices=[(1, 'Fondamental'), (2, 'Secondaire'), (3, 'Superieur')])),
                ('genre', models.IntegerField(choices=[(1, 'Ordinaire'), (2, 'Specialise')])),
                ('type_enseignement', models.CharField(choices=[('prom_soc_sec', 'Promotion sociale secondaire'), ('prom_soc_sup', 'Promotion sociale supérieur'), ('art_hor_red', 'Artistique à horaire réduit'), ('mat_spe', 'Maternel spécialisé'), ('prim_spe', 'Primaire spécialisé'), ('mat_ord', 'Maternel ordinaire'), ('prim_ord', 'Primaire ordinaire'), ('sec_ord', 'Secondaire ordinaire'), ('sec_cefa', 'Secondaire CEFA'), ('sec_spe', 'Secondaire spécialisé'), ('eco_sup_art', 'École supérieure des Arts'), ('prom_soc_cefa', 'Promotion Sociale CEFA'), ('unif', 'Université'), ('he', 'Haute École')], max_length=24)),
            ],
            options={
                'abstract': False,
            },
            bases=('catalogue.georefpostaladdress',),
        ),
    ]
