# Generated by Django 3.2.12 on 2022-04-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwgpostaladdress',
            name='latitude',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='kwgpostaladdress',
            name='longitude',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
