# Generated by Django 3.2.12 on 2022-04-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20220402_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kwgorganization',
            name='bce',
        ),
        migrations.RemoveField(
            model_name='kwgorganization',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='kwgpostaladdress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='kwgpostaladdress',
            name='longitude',
        ),
        migrations.CreateModel(
            name='EtablissementEnseignement',
            fields=[
                ('kwgorganization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.kwgorganization')),
                ('fase', models.CharField(blank=True, max_length=6, null=True)),
                ('bce', models.CharField(blank=True, max_length=15, null=True)),
                ('reseau', models.CharField(blank=True, max_length=255, null=True)),
                ('niveau', models.CharField(blank=True, max_length=255, null=True)),
                ('type_ens', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('catalogue.kwgorganization',),
        ),
    ]
