# Generated by Django 3.2.12 on 2022-04-09 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20220409_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoRefPostalAddress',
            fields=[
                ('kwgpostaladdress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.kwgpostaladdress')),
                ('latitude', models.FloatField(default=0, editable=False)),
                ('longitude', models.FloatField(default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('catalogue.kwgpostaladdress',),
        ),
        migrations.AlterModelOptions(
            name='etablissementenseignement',
            options={'verbose_name': "Etablissement d'enseignement", 'verbose_name_plural': "Etablissements d'enseignement"},
        ),
    ]
