# Generated by Django 3.2.12 on 2022-04-09 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20220409_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='georefpostaladdress',
            options={'verbose_name': 'Adresse postale géoréférencée', 'verbose_name_plural': 'Adresses postales géoréférencées'},
        ),
    ]
