# Generated by Django 3.2.12 on 2022-04-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_georefpostaladdress_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissementenseignement',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='etablissementenseignement',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='etablissementenseignement',
            name='type_ens',
        ),
    ]
