# Generated by Django 3.2.12 on 2022-04-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20220410_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwgpostaladdress',
            name='purpose',
            field=models.CharField(choices=[('O', 'Bureau'), ('S', 'Site'), ('H', 'Domicile'), ('D', 'Point de distribution postal'), ('UD', "Défini par l'utilisateur")], help_text='Identifies the logical location of the address', max_length=2),
        ),
        migrations.AlterField(
            model_name='kwgtelecomaddress',
            name='purpose',
            field=models.CharField(choices=[('O', 'Bureau'), ('S', 'Site'), ('H', 'Domicile'), ('D', 'Point de distribution postal'), ('UD', "Défini par l'utilisateur")], help_text='Identifies the logical location of the address', max_length=2),
        ),
    ]
