# Generated by Django 3.2.12 on 2022-06-06 19:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=124)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Stuck'), (2, 'Working'), (3, 'Done')], default=1)),
                ('date_butoir', models.DateField()),
                ('completude', models.FloatField(max_length=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('assigne', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('localisation', models.ManyToManyField(to='catalogue.GeoRefPostalAddress')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Une liste de mots-clés séparés par une virgule, en minuscule', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Mots-clés')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('status', models.IntegerField(choices=[(1, 'Stuck'), (2, 'Working'), (3, 'Done')], default=1)),
                ('date_butoir', models.DateField(blank=True, null=True)),
                ('delai', models.IntegerField(choices=[(1, 'On Due'), (2, 'Overdue'), (3, 'Done')], default=1)),
                ('assigne', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projet.projet')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Une liste de mots-clés séparés par une virgule, en minuscule', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Mots-clés')),
            ],
            options={
                'ordering': ['projet', 'nom'],
            },
        ),
    ]
