# Generated by Django 3.2.12 on 2022-05-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='localisation',
            field=models.ManyToManyField(to='catalogue.GeoRefPostalAddress'),
        ),
    ]
