# Generated by Django 3.2.12 on 2022-06-06 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('rudi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='docz',
            field=models.ManyToManyField(related_name='documentation', to='rudi.Document'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='assigne',
            field=models.ManyToManyField(related_name='equipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projet',
            name='localisation',
            field=models.ManyToManyField(related_name='endroits', to='catalogue.GeoRefPostalAddress'),
        ),
    ]
