# Generated by Django 3.2.12 on 2022-05-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('projet', '0002_usecase_localisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='effort',
        ),
        migrations.AddField(
            model_name='projet',
            name='localisation',
            field=models.ManyToManyField(to='catalogue.GeoRefPostalAddress'),
        ),
        migrations.DeleteModel(
            name='UseCase',
        ),
    ]
