# Generated by Django 3.2.12 on 2022-06-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('projet', '0002_auto_20220606_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='client',
            field=models.ManyToManyField(related_name='client', to='catalogue.kwgOrganization'),
        ),
    ]
