# Generated by Django 3.2.12 on 2022-05-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_auto_20220525_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projet.projet'),
        ),
    ]
