# Generated by Django 3.2.12 on 2022-06-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rudi', '0001_initial'),
        ('projet', '0004_historicalprojet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='docz',
            field=models.ManyToManyField(related_name='documents_lies', to='rudi.Document'),
        ),
    ]
