# Generated by Django 3.2.12 on 2022-06-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rudi', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('projet', '0006_auto_20220608_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='client',
            field=models.ManyToManyField(null=True, related_name='client', to='catalogue.kwgOrganization'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='docz',
            field=models.ManyToManyField(null=True, related_name='documentation', to='rudi.Document'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='localisation',
            field=models.ManyToManyField(null=True, related_name='endroits', to='catalogue.GeoRefPostalAddress'),
        ),
    ]
