# Generated by Django 3.2.12 on 2022-06-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rudi', '0001_initial'),
        ('projet', '0008_auto_20220608_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='docz',
            field=models.ManyToManyField(blank=True, related_name='documents_lies', to='rudi.Document'),
        ),
    ]
